### ISSUE TITLE
Alpha cleanup (2019-03-12)

### ISSUE THREAD

**Issue by maxfenton** [bluecadet/hscrb-website#67]
- [ ] `single-person` needs related content section -> #48  
- [x] remove light color inverted header
- [x] add additional page header image to Arlotta Lab to show randomization
- [x] fix all icons in Site Header (`search`, `menu`, and `close` icons)
- [x] refactor Faculty/Person `Professional Titles` as a repeater list (bold/normal)
- text style on page header (when over light image) (and test with a Page Header CTA) -> #15 
- [x] abstract on `single-publication` - for AJAX into Flyout -> #40 
- [ ] keep rolling on News page (with Flexible Content fields) -> #46 
- [x] get detail fix list from Sam — padding/margin/opacity

**Comment by samWinfield** [comment]
@maxfenton Short list of F/E fixes, ordered by priority:

 - [ ] Fix all icons in site header (Duplicating your action item above)
 - [ ] for '.bc-c-site-header' the border bottom should be more opaque. Looks like the correct value is in 'border-bottom' but is being overridden by 'border-bottom-color.'
 - [ ] Change 'b,strong' value to 'font-weight: 500' (it is currently 700)
 - [ ] The max width for the body column feels a little narrow. Can we push it to 1240px? (It's currently 1000px)
 - [ ] Publication cards have a lot of white space at the bottom. Looks like it might be the '.bc-c-card--publication__cta' min-height. Can we change to 'min-height: 32px'? (Current value is 172px)
 - [ ] The lab nav has a lot of extra padding. For '.bc-c-lab-nav__item' can we change the padding to 'padding: .5rem 0' ? 
 - [ ] Change '.bc-c-lab-nav__mask' opacity to "opacity:.95;"
 - [ ] There's a lot of extra space at the top of the Lab Principal section. Not sure what's causing it, can we reduce this? (I know this isn't a real fix, but adding a "margin-top:-4rem" to 'bc-l-section bc-c-lab-principal' accomplished the right spacing in chrome.)
